### ISSUE TITLE
2 - Shell Considerações

### ISSUE THREAD

**Issue by tangiota** [guia-de-sobrevivencia-do-programador/Notas-de-Aula#1]
**Comentários Gerais**
- Tenta substituir todos o "a gente" que tiver no texto. Tira um pouco da credibilidade dele. É só tirar e colocar o verbo no pluram que fica mais elegante.
- Será que ficaria legal, pra documentação e consulta, fazer aquele negócio de gravar terminal? acho que ficaria mais visual pra quem fosse só pergar o git ou fazer alguma consulta rápida. 
- Seria legal explicar também que as coisas de bash podem ser feitas tanto diretamente no terminal quanto criar um arquivo em algum editor de texto e depois executá-lo.
- Quando você dá exemplo de código, acho que poderia ser interessante deixar uma explicação sobre o que aquele comando faz, sabe? Fica bem mastigadinho, mas tão bom pra quem tá começando.

**Introdução** 
_> Bash_
4º parágrafo
"O bash pode ser usado de maneira interativa e não interativa. De maneira interativa**,** a shell aceita entrada vinda do teclado (que o usuário está digitando). Já o modo não interativo aceita comandos vindos de outros programas ou de arquivos."

_> Scripts_
2º parágrafo
"Com um conhecimento bom de bash e da suite de programas GNU**,** você consegue automatizar ou simplificar praticamente qualquer aspecto da sua interação com o computador. Desde **como** configurar os seus monitores até uma implementação de docker: tudo é possível."

- Não sei se ficou muito claro que Bash é uma forma de fazer scripts, assim, de uma forma acessível pra quem não conhece nada. Talvez seja legal comentar que python também é usado com essa finalidade por causa disso e disso e daquilo.

**Bash Scripting**
- Tô me perguntando se seria necessário explicar o que seria /bin/bash ou /bin/python3

_>Funções_
"Essas podem ser chamadas como qualquer outro programa (é só digitar o nome) e também podem receber argumentos, mas vamos falar sobre isso mais para frente."

_>Controles de fluxo_
2º parágrafo
- Aqui você diz que "Ao contrário de C...". É só em C que isso acontece, ou tem em outras linguagens? Se tiver, acho que pode deixar mais genérico, tipo "Em scripts em bash, 0 indica verdadeiro e qualquer outro valor, falso."
- Achei que fosse explicar o que o select e o until fazem.

**Ambiente e Variáveis de ambiente**
- Acabei de perceber que eu não tenho certeza se sei o que é um escopo *panic*

3º parágrafo
- Aqui você diz "As variáveis de ambiente tem nomes em caixa alta por costume...". Ao invés de "costume", não seria melhor "convenção"? 

**Rodar múltiplos comandos**
- Acho que vale explicar um pouco mais isso de plano de fundo. Tipo, isso significa que eu posso executar o script em um terminal e continuar fazendo coisas nesse terminal?

**Redirecionamento de E/S**
- O que são pipes e streams? É o mesmo pipe do ||?

_>Redirecionar com arquivos_
- Aqui "O primeiro redirecionamento de entradas e saídas é redirecionar de **_e_** para um arquivo. Para isso você pode utilizar os comandos menor (<) e maior (>) no final do comando." O que é esse e que vou deixar destacado?

"O menor sobrescreve a entrada padrão para**,** em vez de receber do terminal, receber do arquivo que foi passado depois do sinal de menor. O maior sobrescreve a saída padrão para em vez de você escrever no terminal, você escrever em algum arquivo."

_>Redirecionar com outros comandos_
"**Dá** para ver um exemplo com o script ler_arquivo**.**"
Se quiser deixar mais elegante
"Podemos ver um exemplo..." ou "Temos um exemplo..." ou "No script ler_aquivos, colocamos um exemplo de como fazer o redirecionamento com outros comandos". 

_>Redirecionar com outas coisas_
- Aqui, acho que precisa organizar melhor, tipo criar um tópico como vou exemplificar abaixo.
- Redirecionamento de um argumento
Texto Texto Texo. 
- Também não entendi muito bem essas coisas, talvez seja legal ilustrar, ficou bem abstrato. "De um argumento você passa três sinais de menor (<<<) e um argumento depois. Esse argumento pode ser várias coisas dentro de aspas também."

**Comandos avançados**
_Globbing_
- Gostei muito disso aqui. (ex.: **/*.c significa "qualquer coisa nesse diretório e em diretórios abaixo que terminem em .c"). Me deu um exemplo e explicou o exemplo.

**Customização**
2º parágrafo
- Acho que eu tiraria a palavra "roubar". Talvez "inspirar", "testar"?

**Comment by nkzren** [comment]
@JoaoFukuda Eu tô pensando aqui o quanto doq vc colocou na aula 2 não vale a pena explicar na aula 1. A seção de introdução inteira eu acho q caberia lá.

> **Bash Scripting**
> 
> * Tô me perguntando se seria necessário explicar o que seria /bin/bash ou /bin/python3

Eu acho q vale a pena também (talvez na aula 1?). A gnt pode assumir q uma parcela grande do pessoal não vai estar tão habituada com ambiente Linux (mais especificamente, vai estar habituada com Windows), então o `/bin` aí fica meio jogado

**Comment by fnknda** [comment]
Só p avisar que a minha ideia para os READMEs é algo mais parecido com [esses aqui](https://missing.csail.mit.edu/2020/shell-tools/) do Missing Semester mesmo

**Comment by fnknda** [comment]
Ta entregue (eu acho)
