### ISSUE TITLE
Consideracoes sobre a aula 1

### ISSUE THREAD

**Issue by fnknda** [guia-de-sobrevivencia-do-programador/Notas-de-Aula#6]
Tem esses tracos que estao estranhos aqui na sessao de ajuda... precisa ver se n acontece em nenhum outro lugar. ![image](https://user-images.githubusercontent.com/37672942/150899084-12084a1e-095f-4383-bd46-008c583ec295.png)

Favor adicionar o comando `info` em Ajuda tbm.

**Comment by Oiapokxui** [comment]
Feito em 1a6363f
